language: generic
sudo: required
services:
 - docker
script:
 - docker pull linuxataraxia/ataraxia:210328
 - docker run -it --volume ${TRAVIS_BUILD_DIR}:/usr/ports linuxataraxia/ataraxia:210328 /usr/bin/bash -l -c "/usr/bin/ls -la /usr/ports"
