language: c
dist: trusty
sudo: enabled
git:
  submodules: false
addons:
  apt:
    packages:
    - build-essential
    - gcc-multilib
    - bc
    - m4
    - flex
    - bison
    - libtool
    - automake
    - make
    - wget
    - gawk
    - libelf-dev
    - libssl-dev
    - git
script:
- cd /
- git clone https://github.com/JanusLinux/janus.git
- cd janus
- BARCH=x86_64
- ./bootstrap
