language: generic

sudo: required

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install build-essential gcc-multilib m4 wget gawk bc bison flex xorriso libelf-dev libssl-dev texinfo python3 meson ninja-build cmake perl libtool autoconf automake gperf bsdtar libarchive-dev fakeroot -y

script: BARCH=x86_64 ./mk
